// tests/mocks/mock_casbin_service.go

// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CasbinService is an autogenerated mock type for the CasbinService type
type CasbinService struct {
	mock.Mock
}

// CheckPermission provides a mock function with given fields: sub, obj, act
func (_m *CasbinService) CheckPermission(sub string, obj string, act string) bool {
	ret := _m.Called(sub, obj, act)

	if len(ret) == 0 {
		panic("no return value specified for CheckPermission")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(sub, obj, act)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewCasbinService creates a new instance of CasbinService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCasbinService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CasbinService {
	mock := &CasbinService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
